### ISSUE TITLE
Sabnzbd missing incomplete-downloads pvc

### ISSUE THREAD

**Issue by DanielHouston** [aldoborrero/k8s-usenet#5]
I haven't used Helm enough to figure out why this is the case, but deploying sabznd using the default values does not deploy a sabnzbd-incomplete-downloads pvc and so the pod stays in pending.

**Comment by aldoborrero** [comment]
Good eye! I already push the fix to master branch.

Thanks for reporting

**Comment by DanielHouston** [comment]
And thanks for the quick response!
But looks like you updated nzbget and not sabnzbd? It may that it is missing in both

**Comment by aldoborrero** [comment]
Yeah, as I copied those two I "fixed" nzbget thinking it was "sabnzbd"...

Now it should be fixed. Also I updated the charts repository so you can pull directly.

If it is solved mark this issue as solved :) (otherwise let me know if there are more issues)

Thanks for reporting!

**Comment by DanielHouston** [comment]
Looks good to me!
