### ISSUE TITLE
Transmission missing watch-pvc in deployment.yaml

### ISSUE THREAD

**Issue by shutupflanders** [aldoborrero/k8s-usenet#7]
First of all, thanks for your work with these charts!

[deployment.yaml](https://github.com/aldoborrero/k8s-usenet/blob/master/transmission/templates/deployment.yaml)

I'm trying to mount an existing pvc on Transmission for the watch directory, but it doesn't seem to be carried through in the deployment config it should be around line 74 I believe?

**Comment by shutupflanders** [comment]
I've submitted a [PR](https://github.com/aldoborrero/k8s-usenet/pull/8) to hopefully solve this

**Comment by aldoborrero** [comment]
Hi @shutupflanders many thanks for taking your time to fix the transmission chart!

As I stated on the PR, re-open it and we can work together on fixing the issue you're experiencing :)
